### ISSUE TITLE
[BUG] - Randomly turns off other storage options (Disabled by your administrator)

### ISSUE THREAD

**Issue by PS2ClassicsVault** [Minibattle/WinDeckOS#1]
When adding new drives to my system (SD) I have to manually keep setting it to online because the group policy says it was set by my administrator.

Would love this to be fixed so I don't have to keep turning on in the disk manager to enable additional storage.

Hopefully this can be fixed thanks :)

**Comment by Minibattle** [comment]
That's a very strange one, are you using SD cards, or external drives?

**Comment by PS2ClassicsVault** [comment]
External drives

**Comment by Minibattle** [comment]
> Author

Is WinDeckOS installed onto the interanl SSD, or an external drive?

**Comment by PS2ClassicsVault** [comment]
> > Author
> 
> Is WinDeckOS installed onto the interanl SSD, or an external drive?

It's installed on the internal SSD

**Comment by Minibattle** [comment]
> 

I'll look into it, in the meantime if anyone else has this issue - I ask that you please reply here so I can be made aware if the problem is wide spread or not

**Comment by PS2ClassicsVault** [comment]
> > 
> 
> I'll look into it, in the meantime if anyone else has this issue - I ask that you please reply here so I can be made aware if the problem is wide spread or not

Also could I feature request steam deck tools to be in the next version?

**Comment by Minibattle** [comment]
> 

Of course, feel free to feature request anything, just be aware it may or may not be added

**Comment by Bleppyboo** [comment]
So I am not sure if this is applicable here but I am also having storage issues where none of my SD cards are being detected. USB C is fine but I can't even get the drives to show in the Disk Management window

**Comment by Minibattle** [comment]
> 

It's likely related to the file type of the SD card. Could you try putting it in another windows PC and seeing if you have the same issue?

**Comment by PS2ClassicsVault** [comment]
> > 
> 
> It's likely related to the file type of the SD card. Could you try putting it in another windows PC and seeing if you have the same issue?

Well we format them in NTFS

**Comment by Minibattle** [comment]
> 

Could you get it too show up on another windows PC?

**Comment by PS2ClassicsVault** [comment]
> > 
> 
> Could you get it too show up on another windows PC?

I can but requires.me.to go into disk manager and have to go online but eventually.will go back offline cause of administrative issues

**Comment by Minibattle** [comment]
> > > 
> > 
> > 
> > Could you get it too show up on another windows PC?
> 
> I can but requires.me.to go into disk manager and have to go online but eventually.will go back offline cause of administrative issues

That makes it seem like the issue is related to something specific with the way you have windows setup rather than OS
