### ISSUE TITLE
stuttering in all games 

### ISSUE THREAD

**Issue by Yougotnomilk** [Minibattle/WinDeckOS#2]
no matter what game i try it will stutter for a long time then stop and be smooth then stutter again, i have manually downloaded the Windows resources for amd gpu of the steamdeck to try fix the issue but still broken

**Comment by Minibattle** [comment]
Are you installing on the internal SSD?

**Comment by Yougotnomilk** [comment]
yeah i am i just had to retrigger the uma buffer size for some reason that seemed to fix the issue
