### ISSUE TITLE
Changing the C: drive name not possible

### ISSUE THREAD

**Issue by Keremimo** [Minibattle/WinDeckOS#28]
Hello, the name of the C drive in the installation is CCCOMA_X64FRE_EN-US_DV9 and Windows refuses to rename it, also it has a USB flashdrive icon. It looks quite ugly and unnatural. Can this be fixed somehow?

**Comment by MAD-Script** [comment]
Just delete the autorun.inf file in the directory

![Screenshot 2023-10-29 185228](https://github.com/Minibattle/WinDeckOS/assets/44744869/95abb619-0d3b-4afa-995f-a9e8621fe899)

you can also use the autorun to give  set your own drive icon. I made one for WInDeckOS.

https://1drv.ms/u/s!ArHQiOIV13Zsgfhlhxpf0K_0dRW0pA?e=V1LvcU

**Comment by Keremimo** [comment]
Thanks, that'll work out for me. Unfortunately BSOD's prevented me from enjoying it, so had to return to SteamOS.

**Comment by MAD-Script** [comment]
https://www.reddit.com/r/WindowsOnDeck/comments/17j03ok/dual_booting_steamos_and_windeckos/

i have i Tutorial on Dual Booting WindeckOS and SteamOS if youre interested
