### ISSUE TITLE
Steam Deck OLED Support

### ISSUE THREAD

**Issue by Minsekt** [Minibattle/WinDeckOS#30]
will this be updated to have the oled apu/sdcard drivers pre installed and remove the corresponding lcd drivers?
![image](https://github.com/Minibattle/WinDeckOS/assets/103784533/4a6f2a04-1f0e-4a1f-8cea-774255502fab)

**Comment by Minibattle** [comment]
I want to add oled drivers along with the next (and probably last) update, but I do not have an OLED, and even if I did I'd still wait for all the drivers to be added first.

If you know of any ways I could possible install the drivers without an OLED, I'd love to try it.

**Comment by vSouly** [comment]
where do i find those OLED drivers i cant find that page you are on to download them?

**Comment by Minsekt** [comment]
> where do i find those OLED drivers i cant find that page you are on to download them?

https://help.steampowered.com/en/faqs/view/6121-ECCD-D643-BAA8

**Comment by pcthien** [comment]
the drivers for OLED is out now. Can you please support the OLED?
![image](https://github.com/user-attachments/assets/a30ac40d-a31d-44ed-8539-d32d0687f3e3)

**Comment by Minibattle** [comment]
Coming back to say that I have an OLED coming soon and will update the OS for it
