### ISSUE TITLE
hey i can host your builds on my paid dropbox for you! [Not a bug report]

### ISSUE THREAD

**Issue by PS2ClassicsVault** [Minibattle/WinDeckOS#32]
hi, PS2CV here and i can host your OS via dropbox, i pay for premium so unlimited downloads and faster speeds and i can host for free no need to pay me for hosting the file, love your work! hmu @ ps2classicsvault@gmail.com @Minibattle

**Comment by Minibattle** [comment]
I know I am CRAZY late but absolutely go nuts lol
