### ISSUE TITLE
help

### ISSUE THREAD

**Issue by rolexwatch123** [Minibattle/WinDeckOS#33]
is there a .img file instead of mrimg

**Comment by PS2ClassicsVault** [comment]
There is an iso you. Would flash that iso to the usb and then move the windeck file to the root of the usb ans pop it it you deck when your done

**Comment by rolexwatch123** [comment]
where is the iso

**Comment by PS2ClassicsVault** [comment]
In the link i provided it in the zip file

**Comment by rolexwatch123** [comment]
thanks
