### ISSUE TITLE
Can you Use Windows To Go With Windeck OS?

### ISSUE THREAD

**Issue by thanone2** [Minibattle/WinDeckOS#36]
I would like to use Windeck OS on my SD card without touching Steam OS so I could try windows out without messing up anything on my drive if you can link instructions to do that or something I would appreciate it.

**Comment by PS2ClassicsVault** [comment]
Follow the devs tutorial but instead of putting it on your internal ssd out it on your sdcard, just make sure your sdcard is pre-formatted to ntfs or unallocated but backup aby dara on that sdcard first if you have anything important you dont wanna lose

**Comment by thanone2** [comment]
Thanks, I'll try that.

**Comment by thanone2** [comment]
Update: That doesn't work.
I'm going to try making a windows to go SD card then installing Windeck os afterward.

**Comment by thanone2** [comment]
It worked! thanks![]()![20240122_125806.jpg](https://github.com/Minibattle/WinDeckOS/assets/121321813/d6e56060-3093-4089-8f7f-e4a837b634f0)
