### ISSUE TITLE
would you mind updating windows and re-releasing it please?

### ISSUE THREAD

**Issue by thanone2** [Minibattle/WinDeckOS#39]
Just to help other peoples lives, mabye?

**Comment by Xellerate005** [comment]
doesnt it use a fresh install of windows why would you need to update it

**Comment by PS2ClassicsVault** [comment]
> doesnt it use a fresh install of windows why would you need to update it

it definitely needs a OLED release

**Comment by Minibattle** [comment]
Working on both OLED and newer windows version release

**Comment by PS2ClassicsVault** [comment]
Thanks I recommend using tiny11 24H2 as your base OS it's great

**Comment by thanone2** [comment]
> Working on both OLED and newer windows version release

LETS GOOOOO
