### ISSUE TITLE
Good work dude

### ISSUE THREAD

**Issue by mjdd420** [Minibattle/WinDeckOS#4]
Not really a issue just a question, should i leave the apu drivers as is or get the ones on steam page.
BTW ive had a steam deck since release and installed windows by myself since. Some days ago i got word of this project and dude its pretty good, i think i found the primary os for my deck.

**Comment by Minibattle** [comment]
Should leave the APU drivers as the ones in the OS are currently the latest ones. Happy to hear your enjoying the OS
