### ISSUE TITLE
Torrenting when?

### ISSUE THREAD

**Issue by christmaswreath** [Minibattle/WinDeckOS#42]
posted too early since i accidentally clicked the enter button instead of tab. It would be cool to just have a torrent for the project since it would be faster and the community could contribute to it.

**Comment by Minibattle** [comment]
I don't know how to create a torrent, although I have uploaded the project to Google Drive which has pretty good speeds. Anyone who wants to make a torrent of the project should feel free and hopefully let me know so I can link it on the project page.

**Comment by christmaswreath** [comment]
I have the resources to create and seed it, for a lil' while. I will create a PR with the torrent.
