### ISSUE TITLE
(Feature Request) Running Gamepadui before Steam Deck logs in

### ISSUE THREAD

**Issue by rayan629** [Minibattle/WinDeckOS#49]
Hey,
i noticed that the gamepadui takes like a minute to open but with this Project called Gamesdows, it boot directly into the Gamepadui and then after seconds explorer start under it. so it is more like a SteamOS experience.

Here is the Project: [](https://github.com/jazir555/GamesDows)
Greetings Rayan

**Comment by rayan629** [comment]
[https://github.com/jazir555/GamesDows](url)

**Comment by Minibattle** [comment]
This is an absolutely excellent suggestion and the only thing stopping me from adding it is that I would need to publish a new version of WinDeckOS, which can be a bit of a hassle and requires me to do a lot of testing ensuring nothing breaks etc. 

If I update WinDeckOS again, this will 95% be included!
